# Site settings
title: The London Django Meetup Group
email: ''
description: >
    We meet on the 2nd Tuesday of every month to discuss Django, Python, the
    web, and related topics.
baseurl: ''
url: 'http://www.djangolondon.com'

# Build settings
markdown: kramdown
permalink: pretty
exclude:
    - README.md
    - Gemfile
    - Gemfile.lock
    - '*.sublime-project'
collections:
    meetups:
        output: true
        permalink: /meetups/:path/
defaults:
  - scope:
        path: ""
        type: meetups
    values:
        layout: meetup

# deployment
host: 0.0.0.0
port: 4000